[platformio]
default_envs              = esp32s3zero

[env]
  monitor_speed           = 115200
  upload_speed            = 921600
  lib_ldf_mode            = chain+
  lib_deps                = https://github.com/bblanchon/ArduinoJson.git#7.4.x
                            https://github.com/ESP32Async/AsyncTCP.git#v3.4.10
                            https://github.com/ESP32Async/ESPAsyncWebServer.git#v3.10.3
                            adafruit/Adafruit IS31FL3731 Library@2.0.2

[env:esp32s3zero]
  platform                = espressif32
  board                   = esp32-s3-devkitc-1
  framework               = arduino
  upload_protocol         = esptool
  debug_tool              = esp-builtin
  upload_port             = COM12
  monitor_port            = COM12
  board_upload.flash_size = 4MB
  board_build.flash_size  = 4MB
  board_build.partitions  = partitions.csv
  board_build.filesystem  = littlefs
  build_flags             = -D ARDUINOJSON_USE_LONG_LONG=0
                            -D ARDUINOJSON_ENABLE_STD_STRING=0
                            -D ARDUINOJSON_DEFAULT_NESTING_LIMIT=5
                            -D ARDUINO_USB_MODE=1
                            -D ARDUINO_USB_CDC_ON_BOOT=1
                            -D NDEBUG
                            -DCORE_DEBUG_LEVEL=0
                            -Os
                            -Wall
                            -Wno-unused-function
                            -ffunction-sections
                            -fdata-sections
                            -Wl,--gc-sections
                            -Wl,-Map=output.map
                            -Wl,--cref
                            -Wl,--strip-all
  build_unflags           = -fexceptions
                            -fno-exceptions
