[platformio]
default_envs              = esp32s3zero

[env]
  upload_speed            = 921600
  lib_ldf_mode            = chain+
  lib_deps                = https://github.com/bblanchon/ArduinoJson.git#7.4.x
                            https://github.com/ESP32Async/AsyncTCP.git#v3.4.10
                            https://github.com/ESP32Async/ESPAsyncWebServer.git#v3.10.3
                            adafruit/Adafruit IS31FL3731 Library@2.0.2

[env:esp32s3zero]
  platform                = espressif32
  board                   = lolin_s3_mini
  framework               = arduino
  upload_protocol         = esptool
  debug_tool              = esp-builtin

  ; ESP32-S3FH4R2: 4 MB Flash QIO / 2 MB PSRAM QSPI.
  board_upload.flash_size = 4MB
  board_build.flash_size  = 4MB
  board_build.flash_mode  = qio
  board_build.arduino.memory_type = qio_qspi

  board_build.partitions  = partitions.csv
  board_build.filesystem  = littlefs
  extra_scripts           = pre:tools/build_metadata.py

  build_flags             = -D ARDUINOJSON_USE_LONG_LONG=0
                            -D ARDUINOJSON_ENABLE_STD_STRING=0
                            -D ARDUINOJSON_DEFAULT_NESTING_LIMIT=5
                            -D FIRMWARE_VERSION=\"1.5.3\"
                            -D I2C_SDA_PIN=8
                            -D I2C_SCL_PIN=9
                            -D I2C_ISHUTD_PIN=4
                            -D MOON_LED_PIN=21
                            -D ARDUINO_USB_MODE=0
                            -D ARDUINO_USB_CDC_ON_BOOT=0
                            -D ARDUINO_USB_MSC_ON_BOOT=0
                            -D ARDUINO_USB_DFU_ON_BOOT=0
                            -D BOARD_HAS_PSRAM
                            -D NDEBUG
                            -DCORE_DEBUG_LEVEL=0
                            -Os
                            -Wall
                            -Wno-unused-function
                            -ffunction-sections
                            -fdata-sections
                            -Wl,--gc-sections
                            -Wl,-Map=output.map
                            -Wl,--cref
  build_unflags           = -fexceptions
                            -fno-exceptions
                            -DARDUINO_USB_MODE=1
